version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true
skip_commits:
  files:
    - README.md

max_jobs: 1

image: Visual Studio 2015

clone_folder: c:\projects\gibbed-dragonage-savegenerator

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'

install:
  - git submodule update --init --recursive

configuration:
  - Debug

build:
  project: Save Generator.sln
  parallel: true
  verbosity: minimal

before_build:
  - nuget restore
  
after_build:
  - set TZ=GMT
  - git log . > git-log.txt
  - 7z a -r -tzip -mx=9 -x!*/LICENSE.txt savegen-%APPVEYOR_BUILD_VERSION%.zip ./LICENSE.txt ./README.txt ./git-log.txt ./bin/*.exe ./bin/*.config
  - 7z a -r -tzip -mx=9 -x!*/LICENSE.txt savegen-%APPVEYOR_BUILD_VERSION%-with-symbols.zip ./LICENSE.txt ./README.txt ./git-log.txt ./bin/*.exe ./bin/*.config ./bin/*.pdb

artifacts:
  - path: 'savegen-*.zip'
